url = https://tutorialsninja.com/demo/
firstname = Saikrishna
lastname = testing
telephone = 9177396835
validpassword =Saikrishna@1996
emailid = Saikrishna1764702@gmail.com
invalidpassword = 9177396835
Confirmpassword =Saikrishna@1996
emailidtwo =saikrishna91773@gmail.com
validproductone = iMac
nonvalidproduct = chinthapandu 
browserName = chrome